Repository Fraunhofer-AISEC/gallia, pull requests merged in 2022-06, with the labels that each got.

#150 fix(output): revert output for discover-can-ids
  src/gallia/udscan/scanner/find_can_ids.py
Labels: bug

#159 fix(uds): Fix response matching for ClearDiagnosticInformationRequest
  src/gallia/uds/core/service.py
Labels: bug

#165 fix(doip): Fix max TCP connections limitation
  src/gallia/udscan/scanner/discover_doip.py
Labels: bug

#178 chore: Update xcp dependency
  poetry.lock
  pyproject.toml
Labels: dependencies

#171 fix: Allow --oem default in the cli
  CHANGELOG.md
  src/gallia/udscan/core.py
Labels: bug

#174 fix: Let wait_for_ecu() recognize the cli --timeout value
  src/gallia/uds/core/client.py
  src/gallia/uds/ecu.py
Labels: bug, maint

#192 docs: Document the employed scanning techniques
  docs/architecture.md
  docs/automation.md
  docs/conf.py
  docs/index.md
  docs/index.rst
  docs/introduction.md
  docs/penrun.1.rst
  docs/setup.md
  docs/uds/database.md
  docs/uds/scan_modes.md
  docs/uds/virtual_ecu.md
Labels: documentation
