Repository Fraunhofer-AISEC/gallia, pull requests merged in 2022-05, with the labels that each got.

#60 fix: Fix gallia starting whithout "gallia_ecu" endpoint
  src/gallia/udscan/core.py
Labels: bug

#66 fix: Remove stale merge conflict marker
  docs/setup.md
Labels: bug, documentation

#69 chore: Add CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#12 docs: Update README with badges
  README.md
Labels: documentation

#79 fix: Fix dumpcap deadlocking when specifying a nonexistent interface
  src/gallia/penlab.py
Labels: bug

#80 chore(Makefile): Remove hardcoded pytest option
  Makefile
Labels: bug

#95 fix(db): correct index declaration
  src/gallia/db/db_handler.py
Labels: bug

#96 fix: vECU fix wrong db index
  src/gallia/db/db_handler.py
Labels: bug

#111 fix(vecu): set TesterPresent subfunctions to zero subfunction
  src/gallia/uds/core/server.py
Labels: bug

#110 fix(discovery): Better error message for missing targets
  src/gallia/udscan/core.py
  src/gallia/udscan/scanner/find_can_ids.py
Labels: bug

#108 fix(cursed-hr): flush file content
  src/gallia/cursed_hr/cursed_hr.py
Labels: bug

#109 feat(db): Add run stats view
  src/gallia/db/db_handler.py
Labels: enhancement

#117 fix(cli): make auto-completion work again
  src/gallia/cli.py
Labels: bug

#118 fix: Fix broken cli parser
  src/gallia/udscan/core.py
Labels: bug

#119 chore: remove generated files from git
  .github/workflows/docs.yml
  docs/.gitignore
  docs/api/gallia.cursed_hr.rst
  docs/api/gallia.db.rst
  docs/api/gallia.rst
  docs/api/gallia.services.rst
  docs/api/gallia.transports.rst
  docs/api/gallia.uds.core.rst
  docs/api/gallia.uds.rst
  docs/api/gallia.udscan.rst
  docs/api/gallia.udscan.scanner.rst
  docs/api/modules.rst
Labels: documentation

#122 doc: Add overview to README
  README.md
Labels: documentation

#120 docs: Add missing dependencies
  docs/setup.md
Labels: documentation

#113 ci: Add tests against virtual ECU
  .github/workflows/tests.yml
Labels: enhancement, github_actions

#134 docs: Add contribution guide
  CONTRIBUTING.md
  docs/contributing.md
  docs/index.rst
Labels: documentation

#131 fix: Deny all quotes in -T
  bin/penrun
Labels: bug

#128 feat: Add --ping/--no-ping argument to skip initial TesterPresent
  src/gallia/udscan/core.py
Labels: enhancement

#129 fix(can): Allow 0x00 in padding/ext-addressing
  src/gallia/transports/can.py
Labels: bug

#136 feat(cli): Unified output
  src/gallia/db/db_handler.py
  src/gallia/penlab.py
  src/gallia/services/xcp.py
  src/gallia/uds/core/client.py
  src/gallia/uds/core/utils.py
  src/gallia/uds/ecu.py
  src/gallia/udscan/core.py
  src/gallia/udscan/scanner/find_can_ids.py
  src/gallia/udscan/scanner/find_endpoints.py
  src/gallia/udscan/scanner/find_iso_tp_addr.py
  src/gallia/udscan/scanner/find_xcp.py
  src/gallia/udscan/scanner/scan_identifiers.py
  src/gallia/udscan/scanner/scan_memory_functions.py
  src/gallia/udscan/scanner/scan_reset.py
  src/gallia/udscan/scanner/scan_sa_dump_seeds.py
  src/gallia/udscan/scanner/scan_services.py
  src/gallia/udscan/scanner/scan_sessions.py
  src/gallia/udscan/scanner/simple_dtc.py
  src/gallia/udscan/scanner/simple_ecu_reset.py
  src/gallia/udscan/scanner/simple_iocbi.py
  src/gallia/udscan/scanner/simple_ping.py
  src/gallia/udscan/scanner/simple_read_by_identifier.py
  src/gallia/udscan/scanner/simple_read_error_log.py
  src/gallia/udscan/scanner/simple_rmba.py
  src/gallia/udscan/scanner/simple_rtcl.py
  src/gallia/udscan/scanner/simple_send_pdu.py
  src/gallia/udscan/scanner/simple_wmba.py
  src/gallia/udscan/scanner/simple_write_by_identifier.py
  src/gallia/udscan/utils.py
  src/gallia/utils.py
Labels: enhancement

#147 fix: Fix unresolved reference name
  src/gallia/udscan/core.py
Labels: bug

#148 fix: Make the DoIP stack work
  src/gallia/transports/doip.py
Labels: bug
